<upgrade>
    <phrases>
        <phrase>
            <module_id>attachment</module_id>
            <version_id>4.4.0</version_id>
            <var_name>admin_menu_manage</var_name>
            <added>1463048578</added>
            <value>Manage</value>
        </phrase>
    </phrases>
</upgrade>