<upgrade>
	<settings>
		<setting>
			<group>cache</group>
			<module_id>profile</module_id>
			<is_hidden>0</is_hidden>
			<type>boolean</type>
			<var_name>profile_caches</var_name>
			<phrase_var_name>setting_profile_caches</phrase_var_name>
			<ordering>2</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>0</value>
		</setting>
	</settings>
	<phrases>
		<phrase>
			<module_id>profile</module_id>
			<version_id>3.6.0rc1</version_id>
			<var_name>setting_profile_caches</var_name>
			<added>1371724865</added>
			<value><![CDATA[<title>Profile Tracking</title><info>This cache removes the track from profiles. It goes against privacy and is very difficult to circumvent efficiently.</info>]]></value>
		</phrase>
	</phrases>
</upgrade>