<upgrade>
    <phrases>
        <phrase>
            <module_id>photo</module_id>
            <version_id>4.2.1</version_id>
            <var_name>select_photos_s</var_name>
            <added>1453708332</added>
            <value>Select photos(s)</value>
        </phrase>
    </phrases>
    <blocks>
        <block>
            <type_id>0</type_id>
            <m_connection>photo.index</m_connection>
            <module_id>photo</module_id>
            <component>sponsored</component>
            <location>3</location>
            <is_active>1</is_active>
            <ordering>2</ordering>
            <disallow_access/>
            <can_move>0</can_move>
            <title><![CDATA[Sponsored photo]]></title>
            <source_code/>
            <source_parsed/>
        </block>
        <block>
            <type_id>0</type_id>
            <m_connection>photo.index</m_connection>
            <module_id>photo</module_id>
            <component>featured</component>
            <location>3</location>
            <is_active>1</is_active>
            <ordering>1</ordering>
            <disallow_access/>
            <can_move>0</can_move>
            <title><![CDATA[Featured photo]]></title>
            <source_code/>
            <source_parsed/>
        </block>
        <block>
            <type_id>0</type_id>
            <m_connection>photo.index</m_connection>
            <module_id>photo</module_id>
            <component>category</component>
            <location>1</location>
            <is_active>1</is_active>
            <ordering>1</ordering>
            <disallow_access/>
            <can_move>0</can_move>
            <title><![CDATA[Categories]]></title>
            <source_code/>
            <source_parsed/>
        </block>
    </blocks>
</upgrade>
