<upgrade>
    <settings>
        <setting>
            <group>general</group>
            <module_id>user</module_id>
            <is_hidden>0</is_hidden>
            <type>boolean</type>
            <var_name>enable_2step_verification</var_name>
            <phrase_var_name>setting_enable_2step_verification</phrase_var_name>
            <ordering>1</ordering>
            <version_id>4.3.0</version_id>
            <value>0</value>
        </setting>
    </settings>
    <phpfox_update_phrases>
        <phrase>
            <module_id>user</module_id>
            <version_id>2.0.0beta2</version_id>
            <var_name>user_setting_custom_name_field</var_name>
            <added>1242643942</added>
            <value>Custom full name field. Must be phrase, example: user.full_name</value>
        </phrase>
    </phpfox_update_phrases>
    <phrases>
        <phrase>
            <module_id>user</module_id>
            <version_id>4.3.0</version_id>
            <var_name>please_reenter_your_email_again</var_name>
            <added>1444506853</added>
            <value>Please reenter your email again</value>
        </phrase>
        <phrase>
            <module_id>user</module_id>
            <version_id>4.3.0</version_id>
            <var_name>account</var_name>
            <added>1455619900</added>
            <value>Account</value>
        </phrase>
        <phrase>
            <module_id>user</module_id>
            <version_id>4.3.0</version_id>
            <var_name>from</var_name>
            <added>1455769378</added>
            <value>From</value>
        </phrase>
        <phrase>
            <module_id>user</module_id>
            <version_id>4.3.0</version_id>
            <var_name>to</var_name>
            <added>1455769449</added>
            <value>To</value>
        </phrase>
        <phrase>
            <module_id>user</module_id>
            <version_id>4.3.0</version_id>
            <var_name>setting_enable_2step_verification</var_name>
            <added>1455867408</added>
            <value><![CDATA[<title>Enable 2-step verification</title><info>Google Authenticator generates 2-step verification codes on your phone.
Enable 2-step verification to protect your account from hijacking by adding another layer of security. With 2-step verification signing in will require a code generated by the Google Authenticator app in addition to your account password.</info>]]></value>
        </phrase>
        <phrase>
            <module_id>user</module_id>
            <version_id>4.3.0</version_id>
            <var_name>account_verification</var_name>
            <added>1455706343</added>
            <value>Account Verification</value>
        </phrase>
        <phrase>
            <module_id>user</module_id>
            <version_id>4.3.0</version_id>
            <var_name>your_account_has_been_verified_please_log_in_with_the_information_you_provided_during_sign_up</var_name>
            <added>1455792247</added>
            <value>Your account has been verified, please log in with the information you provided during sign up.</value>
        </phrase>
        <phrase>
            <module_id>user</module_id>
            <version_id>4.3.0</version_id>
            <var_name>you_still_need_to_verify_your_account</var_name>
            <added>1455851994</added>
            <value>You still need to verify your account</value>
        </phrase>
        <phrase>
            <module_id>user</module_id>
            <version_id>4.3.0</version_id>
            <var_name>passcode</var_name>
            <added>1455865559</added>
            <value>Passcode</value>
        </phrase>
        <phrase>
            <module_id>user</module_id>
            <version_id>4.3.0</version_id>
            <var_name>dont_receive_passcode_how_to_get_it</var_name>
            <added>1455865785</added>
            <value>Have not received passcode yet, How to get it?</value>
        </phrase>
        <phrase>
            <module_id>user</module_id>
            <version_id>4.3.0</version_id>
            <var_name>how_to_get_passcode</var_name>
            <added>1455867408</added>
            <value>How to get Passcode?</value>
        </phrase>
        <phrase>
            <module_id>user</module_id>
            <version_id>4.3.0</version_id>
            <var_name>google_2step_verify_description</var_name>
            <added>1455866341</added>
            <value><![CDATA[<p><b>Google Authenticator</b> generates 2-step verification codes on your phone.</p>
<p>Enable 2-step verification to protect your account from hijacking by adding another layer of security. With 2-step verification signing in will require a code generated by the <b>Google Authenticator</b> app in addition to your account password.
</p>]]></value>
        </phrase>
        <phrase>
            <module_id>user</module_id>
            <version_id>4.3.0</version_id>
            <var_name>use_google_authencator_app_to_scan_this_qr_code</var_name>
            <added>1455867794</added>
            <value><![CDATA[Use <b>Google Authenticator</b> app to scan this QR Code to get passcode]]></value>
        </phrase>
        <phrase>
            <module_id>user</module_id>
            <version_id>4.3.0</version_id>
            <var_name>enter_your_email</var_name>
            <added>1455870543</added>
            <value>Enter your email</value>
        </phrase>
        <phrase>
            <module_id>user</module_id>
            <version_id>4.3.0</version_id>
            <var_name>invalid_passcode</var_name>
            <added>1455871675</added>
            <value>Invalid Passcode</value>
        </phrase>
        <phrase>
            <module_id>user</module_id>
            <version_id>4.3.0</version_id>
            <var_name>get_new_google_authencator_barcode_when_you_change_email</var_name>
            <added>1455872440</added>
            <value>If you change your email, please scan new Google Authenticator code here</value>
        </phrase>
    </phrases>
</upgrade>
