<upgrade>
    <phrases>
        <phrase>
            <module_id>poll</module_id>
            <version_id>4.4.0</version_id>
            <var_name>design</var_name>
            <added>1459325522</added>
            <value>Design</value>
        </phrase>
    </phrases>
    <phpfox_update_settings>
        <setting>
            <group>time_stamps</group>
            <module_id>poll</module_id>
            <is_hidden>0</is_hidden>
            <type>string</type>
            <var_name>poll_view_time_stamp</var_name>
            <phrase_var_name>setting_poll_view_time_stamp</phrase_var_name>
            <ordering>1</ordering>
            <version_id>2.0.0alpha1</version_id>
            <value>F j, Y</value>
        </setting>
    </phpfox_update_settings>
</upgrade>
